#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackcovy.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hackcovy")]
	public partial class LinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSchedule(Schedule instance);
    partial void UpdateSchedule(Schedule instance);
    partial void DeleteSchedule(Schedule instance);
    partial void InsertResource(Resource instance);
    partial void UpdateResource(Resource instance);
    partial void DeleteResource(Resource instance);
    partial void InsertHistoryAppointment(HistoryAppointment instance);
    partial void UpdateHistoryAppointment(HistoryAppointment instance);
    partial void DeleteHistoryAppointment(HistoryAppointment instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertPrescription(Prescription instance);
    partial void UpdatePrescription(Prescription instance);
    partial void DeletePrescription(Prescription instance);
    partial void InsertDrugInPrescription(DrugInPrescription instance);
    partial void UpdateDrugInPrescription(DrugInPrescription instance);
    partial void DeleteDrugInPrescription(DrugInPrescription instance);
    #endregion
		
		public LinQDataContext() : 
				base(global::Hackcovy.Properties.Settings.Default.HackcovyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Schedule> Schedules
		{
			get
			{
				return this.GetTable<Schedule>();
			}
		}
		
		public System.Data.Linq.Table<Resource> Resources
		{
			get
			{
				return this.GetTable<Resource>();
			}
		}
		
		public System.Data.Linq.Table<HistoryAppointment> HistoryAppointments
		{
			get
			{
				return this.GetTable<HistoryAppointment>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Prescription> Prescriptions
		{
			get
			{
				return this.GetTable<Prescription>();
			}
		}
		
		public System.Data.Linq.Table<Drug> Drugs
		{
			get
			{
				return this.GetTable<Drug>();
			}
		}
		
		public System.Data.Linq.Table<DrugInPrescription> DrugInPrescriptions
		{
			get
			{
				return this.GetTable<DrugInPrescription>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllInfoOfUsers")]
		public ISingleResult<getAllInfoOfUsersResult> getAllInfoOfUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllInfoOfUsersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPrescriptionById")]
		public ISingleResult<getPrescriptionByIdResult> getPrescriptionById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPrescription)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPrescription);
			return ((ISingleResult<getPrescriptionByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllPrescription")]
		public ISingleResult<getAllPrescriptionResult> getAllPrescription()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllPrescriptionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllUsers")]
		public ISingleResult<getAllUsersResult> getAllUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllUsersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllUsersAndPrescription")]
		public ISingleResult<getAllUsersAndPrescriptionResult> getAllUsersAndPrescription()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllUsersAndPrescriptionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDrugInPrescription")]
		public ISingleResult<getDrugInPrescriptionResult> getDrugInPrescription([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPrescription)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPrescription);
			return ((ISingleResult<getDrugInPrescriptionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPrescriptByIdUser")]
		public ISingleResult<getPrescriptByIdUserResult> getPrescriptByIdUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser);
			return ((ISingleResult<getPrescriptByIdUserResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schedule")]
	public partial class Schedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UniqueID;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<bool> _AllDay;
		
		private string _Subject;
		
		private string _Location;
		
		private string _Description;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _Label;
		
		private System.Nullable<int> _ResourceID;
		
		private string _ResourceIDs;
		
		private string _ReminderInfo;
		
		private string _RecurrenceInfo;
		
		private string _TimeZoneId;
		
		private string _CustomField1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(int value);
    partial void OnUniqueIDChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnAllDayChanging(System.Nullable<bool> value);
    partial void OnAllDayChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnLabelChanging(System.Nullable<int> value);
    partial void OnLabelChanged();
    partial void OnResourceIDChanging(System.Nullable<int> value);
    partial void OnResourceIDChanged();
    partial void OnResourceIDsChanging(string value);
    partial void OnResourceIDsChanged();
    partial void OnReminderInfoChanging(string value);
    partial void OnReminderInfoChanged();
    partial void OnRecurrenceInfoChanging(string value);
    partial void OnRecurrenceInfoChanged();
    partial void OnTimeZoneIdChanging(string value);
    partial void OnTimeZoneIdChanged();
    partial void OnCustomField1Changing(string value);
    partial void OnCustomField1Changed();
    #endregion
		
		public Schedule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllDay", DbType="Bit")]
		public System.Nullable<bool> AllDay
		{
			get
			{
				return this._AllDay;
			}
			set
			{
				if ((this._AllDay != value))
				{
					this.OnAllDayChanging(value);
					this.SendPropertyChanging();
					this._AllDay = value;
					this.SendPropertyChanged("AllDay");
					this.OnAllDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Label", DbType="Int")]
		public System.Nullable<int> Label
		{
			get
			{
				return this._Label;
			}
			set
			{
				if ((this._Label != value))
				{
					this.OnLabelChanging(value);
					this.SendPropertyChanging();
					this._Label = value;
					this.SendPropertyChanged("Label");
					this.OnLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceID", DbType="Int")]
		public System.Nullable<int> ResourceID
		{
			get
			{
				return this._ResourceID;
			}
			set
			{
				if ((this._ResourceID != value))
				{
					this.OnResourceIDChanging(value);
					this.SendPropertyChanging();
					this._ResourceID = value;
					this.SendPropertyChanged("ResourceID");
					this.OnResourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceIDs", DbType="NVarChar(MAX)")]
		public string ResourceIDs
		{
			get
			{
				return this._ResourceIDs;
			}
			set
			{
				if ((this._ResourceIDs != value))
				{
					this.OnResourceIDsChanging(value);
					this.SendPropertyChanging();
					this._ResourceIDs = value;
					this.SendPropertyChanged("ResourceIDs");
					this.OnResourceIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReminderInfo", DbType="NVarChar(MAX)")]
		public string ReminderInfo
		{
			get
			{
				return this._ReminderInfo;
			}
			set
			{
				if ((this._ReminderInfo != value))
				{
					this.OnReminderInfoChanging(value);
					this.SendPropertyChanging();
					this._ReminderInfo = value;
					this.SendPropertyChanged("ReminderInfo");
					this.OnReminderInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurrenceInfo", DbType="NVarChar(MAX)")]
		public string RecurrenceInfo
		{
			get
			{
				return this._RecurrenceInfo;
			}
			set
			{
				if ((this._RecurrenceInfo != value))
				{
					this.OnRecurrenceInfoChanging(value);
					this.SendPropertyChanging();
					this._RecurrenceInfo = value;
					this.SendPropertyChanged("RecurrenceInfo");
					this.OnRecurrenceInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZoneId", DbType="NVarChar(MAX)")]
		public string TimeZoneId
		{
			get
			{
				return this._TimeZoneId;
			}
			set
			{
				if ((this._TimeZoneId != value))
				{
					this.OnTimeZoneIdChanging(value);
					this.SendPropertyChanging();
					this._TimeZoneId = value;
					this.SendPropertyChanged("TimeZoneId");
					this.OnTimeZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomField1", DbType="NVarChar(MAX)")]
		public string CustomField1
		{
			get
			{
				return this._CustomField1;
			}
			set
			{
				if ((this._CustomField1 != value))
				{
					this.OnCustomField1Changing(value);
					this.SendPropertyChanging();
					this._CustomField1 = value;
					this.SendPropertyChanged("CustomField1");
					this.OnCustomField1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resources")]
	public partial class Resource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UniqueID;
		
		private int _ResourceID;
		
		private string _ResourceName;
		
		private System.Nullable<int> _Color;
		
		private System.Data.Linq.Binary _Image;
		
		private string _CustomField1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(int value);
    partial void OnUniqueIDChanged();
    partial void OnResourceIDChanging(int value);
    partial void OnResourceIDChanged();
    partial void OnResourceNameChanging(string value);
    partial void OnResourceNameChanged();
    partial void OnColorChanging(System.Nullable<int> value);
    partial void OnColorChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnCustomField1Changing(string value);
    partial void OnCustomField1Changed();
    #endregion
		
		public Resource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceID", DbType="Int NOT NULL")]
		public int ResourceID
		{
			get
			{
				return this._ResourceID;
			}
			set
			{
				if ((this._ResourceID != value))
				{
					this.OnResourceIDChanging(value);
					this.SendPropertyChanging();
					this._ResourceID = value;
					this.SendPropertyChanged("ResourceID");
					this.OnResourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(50)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this.OnResourceNameChanging(value);
					this.SendPropertyChanging();
					this._ResourceName = value;
					this.SendPropertyChanged("ResourceName");
					this.OnResourceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="Int")]
		public System.Nullable<int> Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomField1", DbType="NVarChar(MAX)")]
		public string CustomField1
		{
			get
			{
				return this._CustomField1;
			}
			set
			{
				if ((this._CustomField1 != value))
				{
					this.OnCustomField1Changing(value);
					this.SendPropertyChanging();
					this._CustomField1 = value;
					this.SendPropertyChanged("CustomField1");
					this.OnCustomField1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoryAppointment")]
	public partial class HistoryAppointment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idHistoryAppointment;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<System.TimeSpan> _time;
		
		private string _specialist;
		
		private string _status;
		
		private System.Nullable<int> _idUser;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHistoryAppointmentChanging(int value);
    partial void OnidHistoryAppointmentChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OntimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeChanged();
    partial void OnspecialistChanging(string value);
    partial void OnspecialistChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnidUserChanging(System.Nullable<int> value);
    partial void OnidUserChanged();
    #endregion
		
		public HistoryAppointment()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHistoryAppointment", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idHistoryAppointment
		{
			get
			{
				return this._idHistoryAppointment;
			}
			set
			{
				if ((this._idHistoryAppointment != value))
				{
					this.OnidHistoryAppointmentChanging(value);
					this.SendPropertyChanging();
					this._idHistoryAppointment = value;
					this.SendPropertyChanged("idHistoryAppointment");
					this.OnidHistoryAppointmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialist", DbType="NVarChar(100)")]
		public string specialist
		{
			get
			{
				return this._specialist;
			}
			set
			{
				if ((this._specialist != value))
				{
					this.OnspecialistChanging(value);
					this.SendPropertyChanging();
					this._specialist = value;
					this.SendPropertyChanged("specialist");
					this.OnspecialistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(100)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int")]
		public System.Nullable<int> idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_HistoryAppointment", Storage="_User", ThisKey="idUser", OtherKey="idUser", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.HistoryAppointments.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.HistoryAppointments.Add(this);
						this._idUser = value.idUser;
					}
					else
					{
						this._idUser = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUser;
		
		private string _email;
		
		private string _fullName;
		
		private string _phoneNumber;
		
		private string _pictureProfile;
		
		private string _address;
		
		private string _yearOfBirth;
		
		private string _gender;
		
		private EntitySet<HistoryAppointment> _HistoryAppointments;
		
		private EntitySet<Prescription> _Prescriptions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OnpictureProfileChanging(string value);
    partial void OnpictureProfileChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnyearOfBirthChanging(string value);
    partial void OnyearOfBirthChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    #endregion
		
		public User()
		{
			this._HistoryAppointments = new EntitySet<HistoryAppointment>(new Action<HistoryAppointment>(this.attach_HistoryAppointments), new Action<HistoryAppointment>(this.detach_HistoryAppointments));
			this._Prescriptions = new EntitySet<Prescription>(new Action<Prescription>(this.attach_Prescriptions), new Action<Prescription>(this.detach_Prescriptions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(12)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureProfile", DbType="NVarChar(MAX)")]
		public string pictureProfile
		{
			get
			{
				return this._pictureProfile;
			}
			set
			{
				if ((this._pictureProfile != value))
				{
					this.OnpictureProfileChanging(value);
					this.SendPropertyChanging();
					this._pictureProfile = value;
					this.SendPropertyChanged("pictureProfile");
					this.OnpictureProfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearOfBirth", DbType="NVarChar(50)")]
		public string yearOfBirth
		{
			get
			{
				return this._yearOfBirth;
			}
			set
			{
				if ((this._yearOfBirth != value))
				{
					this.OnyearOfBirthChanging(value);
					this.SendPropertyChanging();
					this._yearOfBirth = value;
					this.SendPropertyChanged("yearOfBirth");
					this.OnyearOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_HistoryAppointment", Storage="_HistoryAppointments", ThisKey="idUser", OtherKey="idUser")]
		public EntitySet<HistoryAppointment> HistoryAppointments
		{
			get
			{
				return this._HistoryAppointments;
			}
			set
			{
				this._HistoryAppointments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Prescription", Storage="_Prescriptions", ThisKey="idUser", OtherKey="idUser")]
		public EntitySet<Prescription> Prescriptions
		{
			get
			{
				return this._Prescriptions;
			}
			set
			{
				this._Prescriptions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistoryAppointments(HistoryAppointment entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_HistoryAppointments(HistoryAppointment entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Prescriptions(Prescription entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Prescriptions(Prescription entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prescription")]
	public partial class Prescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser;
		
		private string _emailShare;
		
		private EntitySet<DrugInPrescription> _DrugInPrescriptions;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPrescriptionChanging(int value);
    partial void OnidPrescriptionChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    partial void OndiagnosticChanging(string value);
    partial void OndiagnosticChanged();
    partial void OnreExaminationChanging(string value);
    partial void OnreExaminationChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnidUserChanging(System.Nullable<int> value);
    partial void OnidUserChanged();
    partial void OnemailShareChanging(string value);
    partial void OnemailShareChanged();
    #endregion
		
		public Prescription()
		{
			this._DrugInPrescriptions = new EntitySet<DrugInPrescription>(new Action<DrugInPrescription>(this.attach_DrugInPrescriptions), new Action<DrugInPrescription>(this.detach_DrugInPrescriptions));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this.OnidPrescriptionChanging(value);
					this.SendPropertyChanging();
					this._idPrescription = value;
					this.SendPropertyChanged("idPrescription");
					this.OnidPrescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this.OndiagnosticChanging(value);
					this.SendPropertyChanging();
					this._diagnostic = value;
					this.SendPropertyChanged("diagnostic");
					this.OndiagnosticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this.OnreExaminationChanging(value);
					this.SendPropertyChanging();
					this._reExamination = value;
					this.SendPropertyChanged("reExamination");
					this.OnreExaminationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int")]
		public System.Nullable<int> idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailShare", DbType="NVarChar(MAX)")]
		public string emailShare
		{
			get
			{
				return this._emailShare;
			}
			set
			{
				if ((this._emailShare != value))
				{
					this.OnemailShareChanging(value);
					this.SendPropertyChanging();
					this._emailShare = value;
					this.SendPropertyChanged("emailShare");
					this.OnemailShareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescription_DrugInPrescription", Storage="_DrugInPrescriptions", ThisKey="idPrescription", OtherKey="idPrescription")]
		public EntitySet<DrugInPrescription> DrugInPrescriptions
		{
			get
			{
				return this._DrugInPrescriptions;
			}
			set
			{
				this._DrugInPrescriptions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Prescription", Storage="_User", ThisKey="idUser", OtherKey="idUser", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Prescriptions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Prescriptions.Add(this);
						this._idUser = value.idUser;
					}
					else
					{
						this._idUser = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DrugInPrescriptions(DrugInPrescription entity)
		{
			this.SendPropertyChanging();
			entity.Prescription = this;
		}
		
		private void detach_DrugInPrescriptions(DrugInPrescription entity)
		{
			this.SendPropertyChanging();
			entity.Prescription = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Drug")]
	public partial class Drug
	{
		
		private int _id;
		
		private string _drugName;
		
		private string _color;
		
		private string _image;
		
		public Drug()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drugName", DbType="NVarChar(150)")]
		public string drugName
		{
			get
			{
				return this._drugName;
			}
			set
			{
				if ((this._drugName != value))
				{
					this._drugName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DrugInPrescription")]
	public partial class DrugInPrescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDrug;
		
		private string _drugName;
		
		private System.Nullable<int> _dosage;
		
		private string _time;
		
		private System.Nullable<int> _amountOfMedicine;
		
		private System.Nullable<int> _idPrescription;
		
		private string _image;
		
		private string _color;
		
		private EntityRef<Prescription> _Prescription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDrugChanging(int value);
    partial void OnidDrugChanged();
    partial void OndrugNameChanging(string value);
    partial void OndrugNameChanged();
    partial void OndosageChanging(System.Nullable<int> value);
    partial void OndosageChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnamountOfMedicineChanging(System.Nullable<int> value);
    partial void OnamountOfMedicineChanged();
    partial void OnidPrescriptionChanging(System.Nullable<int> value);
    partial void OnidPrescriptionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    #endregion
		
		public DrugInPrescription()
		{
			this._Prescription = default(EntityRef<Prescription>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDrug", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDrug
		{
			get
			{
				return this._idDrug;
			}
			set
			{
				if ((this._idDrug != value))
				{
					this.OnidDrugChanging(value);
					this.SendPropertyChanging();
					this._idDrug = value;
					this.SendPropertyChanged("idDrug");
					this.OnidDrugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drugName", DbType="NVarChar(150)")]
		public string drugName
		{
			get
			{
				return this._drugName;
			}
			set
			{
				if ((this._drugName != value))
				{
					this.OndrugNameChanging(value);
					this.SendPropertyChanging();
					this._drugName = value;
					this.SendPropertyChanged("drugName");
					this.OndrugNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosage", DbType="Int")]
		public System.Nullable<int> dosage
		{
			get
			{
				return this._dosage;
			}
			set
			{
				if ((this._dosage != value))
				{
					this.OndosageChanging(value);
					this.SendPropertyChanging();
					this._dosage = value;
					this.SendPropertyChanged("dosage");
					this.OndosageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(150)")]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountOfMedicine", DbType="Int")]
		public System.Nullable<int> amountOfMedicine
		{
			get
			{
				return this._amountOfMedicine;
			}
			set
			{
				if ((this._amountOfMedicine != value))
				{
					this.OnamountOfMedicineChanging(value);
					this.SendPropertyChanging();
					this._amountOfMedicine = value;
					this.SendPropertyChanged("amountOfMedicine");
					this.OnamountOfMedicineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int")]
		public System.Nullable<int> idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					if (this._Prescription.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPrescriptionChanging(value);
					this.SendPropertyChanging();
					this._idPrescription = value;
					this.SendPropertyChanged("idPrescription");
					this.OnidPrescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(150)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescription_DrugInPrescription", Storage="_Prescription", ThisKey="idPrescription", OtherKey="idPrescription", IsForeignKey=true)]
		public Prescription Prescription
		{
			get
			{
				return this._Prescription.Entity;
			}
			set
			{
				Prescription previousValue = this._Prescription.Entity;
				if (((previousValue != value) 
							|| (this._Prescription.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prescription.Entity = null;
						previousValue.DrugInPrescriptions.Remove(this);
					}
					this._Prescription.Entity = value;
					if ((value != null))
					{
						value.DrugInPrescriptions.Add(this);
						this._idPrescription = value.idPrescription;
					}
					else
					{
						this._idPrescription = default(Nullable<int>);
					}
					this.SendPropertyChanged("Prescription");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class getAllInfoOfUsersResult
	{
		
		private int _idUser;
		
		private string _email;
		
		private string _fullName;
		
		private string _phoneNumber;
		
		private string _pictureProfile;
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser1;
		
		private int _idDrug;
		
		private string _drugName;
		
		private System.Nullable<int> _dosage;
		
		private string _time;
		
		private System.Nullable<int> _amountOfMedicine;
		
		private System.Nullable<int> _idPrescription1;
		
		private string _image;
		
		private string _color;
		
		public getAllInfoOfUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int NOT NULL")]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(12)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureProfile", DbType="NVarChar(MAX)")]
		public string pictureProfile
		{
			get
			{
				return this._pictureProfile;
			}
			set
			{
				if ((this._pictureProfile != value))
				{
					this._pictureProfile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int NOT NULL")]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this._diagnostic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this._reExamination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser1", DbType="Int")]
		public System.Nullable<int> idUser1
		{
			get
			{
				return this._idUser1;
			}
			set
			{
				if ((this._idUser1 != value))
				{
					this._idUser1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDrug", DbType="Int NOT NULL")]
		public int idDrug
		{
			get
			{
				return this._idDrug;
			}
			set
			{
				if ((this._idDrug != value))
				{
					this._idDrug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drugName", DbType="NVarChar(150)")]
		public string drugName
		{
			get
			{
				return this._drugName;
			}
			set
			{
				if ((this._drugName != value))
				{
					this._drugName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosage", DbType="Int")]
		public System.Nullable<int> dosage
		{
			get
			{
				return this._dosage;
			}
			set
			{
				if ((this._dosage != value))
				{
					this._dosage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(150)")]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountOfMedicine", DbType="Int")]
		public System.Nullable<int> amountOfMedicine
		{
			get
			{
				return this._amountOfMedicine;
			}
			set
			{
				if ((this._amountOfMedicine != value))
				{
					this._amountOfMedicine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription1", DbType="Int")]
		public System.Nullable<int> idPrescription1
		{
			get
			{
				return this._idPrescription1;
			}
			set
			{
				if ((this._idPrescription1 != value))
				{
					this._idPrescription1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(150)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
	}
	
	public partial class getPrescriptionByIdResult
	{
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser;
		
		public getPrescriptionByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int NOT NULL")]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this._diagnostic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this._reExamination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int")]
		public System.Nullable<int> idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
	}
	
	public partial class getAllPrescriptionResult
	{
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser;
		
		public getAllPrescriptionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int NOT NULL")]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this._diagnostic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this._reExamination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int")]
		public System.Nullable<int> idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
	}
	
	public partial class getAllUsersResult
	{
		
		private int _idUser;
		
		private string _email;
		
		private string _fullName;
		
		private string _phoneNumber;
		
		private string _pictureProfile;
		
		public getAllUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int NOT NULL")]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(12)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureProfile", DbType="NVarChar(MAX)")]
		public string pictureProfile
		{
			get
			{
				return this._pictureProfile;
			}
			set
			{
				if ((this._pictureProfile != value))
				{
					this._pictureProfile = value;
				}
			}
		}
	}
	
	public partial class getAllUsersAndPrescriptionResult
	{
		
		private int _idUser;
		
		private string _email;
		
		private string _fullName;
		
		private string _phoneNumber;
		
		private string _pictureProfile;
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser1;
		
		public getAllUsersAndPrescriptionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int NOT NULL")]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(12)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureProfile", DbType="NVarChar(MAX)")]
		public string pictureProfile
		{
			get
			{
				return this._pictureProfile;
			}
			set
			{
				if ((this._pictureProfile != value))
				{
					this._pictureProfile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int NOT NULL")]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this._diagnostic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this._reExamination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser1", DbType="Int")]
		public System.Nullable<int> idUser1
		{
			get
			{
				return this._idUser1;
			}
			set
			{
				if ((this._idUser1 != value))
				{
					this._idUser1 = value;
				}
			}
		}
	}
	
	public partial class getDrugInPrescriptionResult
	{
		
		private int _idDrug;
		
		private string _drugName;
		
		private System.Nullable<int> _dosage;
		
		private string _time;
		
		private System.Nullable<int> _amountOfMedicine;
		
		private System.Nullable<int> _idPrescription;
		
		private string _image;
		
		private string _color;
		
		public getDrugInPrescriptionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDrug", DbType="Int NOT NULL")]
		public int idDrug
		{
			get
			{
				return this._idDrug;
			}
			set
			{
				if ((this._idDrug != value))
				{
					this._idDrug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drugName", DbType="NVarChar(150)")]
		public string drugName
		{
			get
			{
				return this._drugName;
			}
			set
			{
				if ((this._drugName != value))
				{
					this._drugName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosage", DbType="Int")]
		public System.Nullable<int> dosage
		{
			get
			{
				return this._dosage;
			}
			set
			{
				if ((this._dosage != value))
				{
					this._dosage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(150)")]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountOfMedicine", DbType="Int")]
		public System.Nullable<int> amountOfMedicine
		{
			get
			{
				return this._amountOfMedicine;
			}
			set
			{
				if ((this._amountOfMedicine != value))
				{
					this._amountOfMedicine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int")]
		public System.Nullable<int> idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(150)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
	}
	
	public partial class getPrescriptByIdUserResult
	{
		
		private int _idPrescription;
		
		private string _notes;
		
		private string _diagnostic;
		
		private string _reExamination;
		
		private string _date;
		
		private System.Nullable<int> _idUser;
		
		public getPrescriptByIdUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrescription", DbType="Int NOT NULL")]
		public int idPrescription
		{
			get
			{
				return this._idPrescription;
			}
			set
			{
				if ((this._idPrescription != value))
				{
					this._idPrescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(150)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnostic", DbType="NVarChar(150)")]
		public string diagnostic
		{
			get
			{
				return this._diagnostic;
			}
			set
			{
				if ((this._diagnostic != value))
				{
					this._diagnostic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reExamination", DbType="NVarChar(150)")]
		public string reExamination
		{
			get
			{
				return this._reExamination;
			}
			set
			{
				if ((this._reExamination != value))
				{
					this._reExamination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="Int")]
		public System.Nullable<int> idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this._idUser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
